##Recuperar peliculas con paginación##
GET http://172.19.14.135:5000/api/v1/channel
##Recuperar peliculas con paginación###
GET http://172.19.14.135:5000/api/v1/channel/all
##Recuperar los Ususarios###

GET http://172.19.14.135:5000/api/v1/user

##Recuperar un Canal por su id ###

GET http://172.19.14.135:5000/api/v1/channel/6758c09cbae8554830d98e02